apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-example
  name: echo-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-example
  template:
    metadata:
      labels:
        app: echo-example
    spec:
      containers:
      - image: dockersamples/echo-example
        name: echo-example
